[package]
name = "slice_and_dice"
version = "0.1.0"
edition = "2021"

[dependencies]
peano = "1.0.2"
itertools = "0.14.0"
serde = { version = "1.0", features = ["derive"], optional = true }
num-traits = "0.2"

[features]
serde = ["dep:serde"]
